<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "goodsattach".
 *
 * @property string $id
 * @property string $goodsID
 * @property int $ver
 * @property int $type
 * @property string $url
 * @property int $sort
 * @property string $addAt
 * @property string $addBy
 * @property string $addIP
 * @property string $addAgent
 */
class Goodsattach extends \yii\db\ActiveRecord
{
    // 文件类型
    private static $type = [
        0 => '图片',
        1 => '视频',
    ];

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'goodsattach';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['ver', 'type', 'sort', 'addAt'], 'integer'],
            [['id', 'goodsID', 'addBy'], 'string', 'max' => 32],
            [['url', 'addAgent'], 'string', 'max' => 300],
            [['addIP'], 'string', 'max' => 100],
            [['id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'goodsID' => 'Goods ID',
            'ver' => 'Ver',
            'type' => 'Type',
            'url' => 'Url',
            'sort' => 'Sort',
            'addAt' => 'Add At',
            'addBy' => 'Add By',
            'addIP' => 'Add Ip',
            'addAgent' => 'Add Agent',
        ];
    }
//
//    public function fields()
//    {
//        return [
//            'id',
//            'goodsID',
//            'type',
//            'url',
//            'addAt',
//            'addBy'
//        ]; // TODO: Change the autogenerated stub
//    }

    /**
     * 根据节点id 获取商品信息
     * @param $id
     * @return array
     */
    public static function getAttachByGoodsID($id)
    {
        //查出最新版本
        $ver = self::find()->where(['goodsID' => $id, 'type' => '0'])->orderBy(['ver' => SORT_DESC])->one();

        return self::find()->where(['goodsID' => $id, 'type' => '0', 'ver' => $ver->ver])->all();
    }

    public function addAttach($param,$type)
    {
        try{
            //addAt
            $this->addAt = strtotime(date("Y-m-d H:i:s"));
            $this->ver = "1";
            $this->type = $type;
            $this->attributes = $param;
            if(false === $this->save()){
                return ['code' => -3, 'data' => '', 'msg' => array_values($this->errors)['0']['0']];
            }
        }catch (\Exception $e){

            return ['code' => -1, 'data' => '', 'msg' => $e->getMessage()];
        }

        return ['code' => 1, 'data' => '', 'msg' => '添加goodsAttach成功'];
    }
}
